### ISSUE TITLE
Add hint to centralized device picture repository

### ISSUE THREAD

**Issue by maurerle** [nalxnet/freifunk-device-images#2]
A centralized approach is now living and available at https://github.com/freifunk/device-pictures

If you would like to help lead visitors to the centralized repository, it would be very cool to add a hint to the central repository in the repo description or Readme.

For example as can be seen here: https://github.com/belzebub40k/router-pics

**Comment by nalxnet** [comment]
Thanks for the hint, I've added the links and will archive this repo.
